### ISSUE TITLE
这个插件适配1.10.2吗。。

### ISSUE THREAD

**Issue by chenxuuu** [aegistudio/MapCircuitBoard#1]
感觉前置和这个插件都没写1.10.2啊😂

**Comment by andylizi** [comment]
作者没更新了自然不会写。

**Comment by aegistudio** [comment]
@chenxuuu @andylizi 1.12
![screenshot from 2017-08-18 16-08-45](https://user-images.githubusercontent.com/6104287/29450057-bd659730-842f-11e7-8ff3-e04a21716593.png)
似乎没改接口，还能再战十年
